name: backup.sh
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install rsync tar openssl shellcheck
      - name: Run ShellCheck
        run: |
          shellcheck backup.sh
          shellcheck tests.sh
      - name: Install using Makefile
        run: |
          sudo make install
      - name: Run unit tests
        run: |
          sudo ./tests.sh I_HAVE_READ_THE_HELPER
